Repository MixUpTeam/MixUpBack, pull requests merged in 2020-06, with the labels that each got.

#23 15 create shordhand methods
  app/models/playlist.rb
  app/models/track_playlist.rb
  app/models/user.rb
Labels: priority

#24 20 function display a playlist
  app/controllers/application_controller.rb
  app/controllers/playlists_controller.rb
Labels: priority

#25 22 add track to playlist
  app/controllers/application_controller.rb
  app/controllers/playlists_controller.rb
  app/controllers/track_playlists_controller.rb
Labels: priority

#42 hot fix vote_weight to act_as_votable migration
  db/migrate/20200622080134_acts_as_votable_migration.rb
  db/schema.rb
Labels: priority

#37 38 Test and ci
  .rspec
  .rubocop.yml
  .travis.yml
  Gemfile
  Gemfile.lock
  app/controllers/api/api_controller.rb
  app/controllers/api/v1/track_playlists_controller.rb
  app/controllers/application_controller.rb
  spec/controllers/playlists_controller_spec.rb
  spec/controllers/track_playlists_controller_spec.rb
  spec/controllers/user_profiles_controller_spec.rb
  spec/factories/playlists.rb
  spec/factories/track_playlists.rb
  spec/factories/user_profiles.rb
  spec/factories/users.rb
  spec/models/playlist_spec.rb
  spec/models/track_playlist_spec.rb
  spec/models/user_profile_spec.rb
  spec/models/user_spec.rb
  spec/rails_helper.rb
  spec/requests/playlists_spec.rb
  spec/requests/track_playlists_spec.rb
  spec/requests/user_profiles_spec.rb
  spec/routing/playlists_routing_spec.rb
  spec/routing/track_playlists_routing_spec.rb
  spec/routing/user_profiles_routing_spec.rb
  spec/spec_helper.rb
  spec/support/database_cleaner.rb
  spec/support/factory_bot.rb
Labels: DevOps, minor

#44 34 function user auth
  .env.development
  app/controllers/application_controller.rb
  app/models/jwt_blacklist.rb
  app/models/user.rb
  config/initializers/devise.rb
  config/routes.rb
  db/migrate/20200623084638_create_jwt_blacklist.rb
  db/schema.rb
  spec/rails_helper.rb
  spec/requests/users_spec.rb
  spec/support/devise_request_spec_helpers.rb
Labels: back

#47 #46 function get current user
  app/controllers/api/api_controller.rb
  app/controllers/api/v1/playlists_controller.rb
  app/controllers/api/v1/track_playlists_controller.rb
  app/controllers/application_controller.rb
  skip.travis.yml
Labels: back

#49 #30 function change the is playing is played status of a track playlist
  app/controllers/api/v1/playlists_controller.rb
  app/controllers/api/v1/track_playlists_controller.rb
  app/models/track_playlist.rb
  config/routes.rb
Labels: back

#50 Hot fix 30
  app/controllers/api/v1/playlists_controller.rb
  app/controllers/api/v1/track_playlists_controller.rb
  app/models/playlist.rb
Labels: back, priority

#51 [fix] playlist model typo
  app/models/playlist.rb
Labels: back

#52 48-update-readme
  README.md
Labels: back

#54 #53 finish_track method to track_playlists_controller
  app/controllers/api/v1/track_playlists_controller.rb
Labels: back
